services:
  localstack:
    container_name: localstack
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - DEBUG=0
      - PERSISTENCE=0
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped


