services:
  localstack:
    container_name: localstack
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - DEBUG=0
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///run/podman/podman.sock
    volumes:
      - "./volume:/var/lib/localstack"
      - "/run/podman/podman.sock:/var/run/docker.sock:ro"
    restart: unless-stopped


