version: "3.8"

services:
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.svc.assistance.bg:21117
    volumes:
      - rustdesk_data:/root
    networks:
      - rustdesk-net
    ports:
      - "21115:21115/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
      - "21118:21118/tcp"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - rustdesk_data:/root
    networks:
      - rustdesk-net
    ports:
      - "21117:21117/tcp"
      - "21119:21119/tcp"
    restart: unless-stopped

volumes:
  rustdesk_data:
    driver: local

networks:
  rustdesk-net:
    driver: bridge
